theme: minima
title: Getting Started With GitHub
author: s-m-quadri
email: quadrisyedminnatullah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description in GitHub Getting statarted with page 
  tutorials.
# Is it comments
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  s-m-quadri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
